# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHeoDeyCBVa1FU-a43lIOKRcKQeEhRgc
"""

import streamlit as st
import requests
import pandas as pd

# 📌 Replace with your API key from https://www.alphavantage.co/support/#api-key
API_KEY = "YOUR_API_KEY"

def get_stock_price(symbol):
    """Fetches the latest stock price for a given symbol using Alpha Vantage API."""
    url = f"https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={symbol}&apikey={API_KEY}"
    response = requests.get(url).json()
    return response.get("Global Quote", {}).get("05. price", "N/A")

def get_crypto_price(crypto):
    """Fetches the latest crypto price using CoinGecko API."""
    url = f"https://api.coingecko.com/api/v3/simple/price?ids={crypto}&vs_currencies=usd"
    response = requests.get(url).json()
    return response.get(crypto, {}).get("usd", "N/A")

# 🎨 Streamlit UI
st.title("📈 Real-time Stock & Crypto Price Tracker")

# User input for stocks and crypto
option = st.selectbox("Select Asset Type", ["Stock", "Crypto"])
symbol = st.text_input("Enter Symbol (e.g., AAPL, bitcoin)")

if st.button("Get Price"):
    if option == "Stock":
        price = get_stock_price(symbol)
    else:
        price = get_crypto_price(symbol.lower())

    st.success(f"Current Price of {symbol.upper()}: {price} USD")